### ISSUE TITLE
Add language slot option

### ISSUE THREAD

**Issue by DraganRatkovich** [addonFactory/instantTranslate#26] opened 2023-10-05 15:09 UTC
Hi,

I came across several discussions about this feature in several Telegram groups, and since I know that you are planning to rewrite the add-on from scratch, I am opening this issue on GitHub to save it as history for future implementation in the add-on.

It will be a nice feature if you add a favorite language slot option. If the user wants to translate from English to Russian or from Russian to German, he can assign different slots and gestures to the slot to quickly switch to the favorite language selected for translation.

Perhaps no slot is required and all it takes is a gesture to create your favorite language set for translation, but how you choose to implement this is up to you.

**Comment by beqabeqa473** [comment] 2024-03-22 07:26
I'd like to call it language pear profiles, which could be toggled either from layerd gesture with shift+0-9 or to bind a gesture.

**Comment by beqabeqa473** [comment] 2024-03-22 07:28
duplicate of #19

**Closed as completed by beqabeqa473** 2024-03-22 07:28 UTC
